#### Exercise 4.01 – underlying data types and conversion

In [1]:
import pandas as pd

In [2]:
file_url = 'files/Chapter04/Data/retail_purchase.csv'
data_frame = pd.read_csv(file_url)
data_frame.head()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
0,10001,24/05/20,Wheat,4.8lb,€17,Fline Store
1,10002,05/05/20,Fruit Juice,3.1lb,€19,Dello Superstore
2,10003,27/04/20,Vegetables,1.2lb,€15,Javies Retail
3,10004,05/05/20,Oil,3.1lb,€17,Javies Retail
4,10005,27/04/20,Wheat,4.8lb,€13,Javies Retail

In [3]:
data_frame.tail()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
99995,109996,24/05/20,Oil,4.8lb,€25,Visco Retail
99996,109997,20/04/20,Rice,3.1lb,€12,Kelly Superstore
99997,109998,08/01/20,Fruit Juice,2.7lb,€24,Dello Superstore
99998,109999,05/05/20,Butter,3.1lb,€22,Dello Superstore
99999,110000,17/04/20,Bread,4.4lb,€27,Visco Retail

In [4]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Receipt Id        100000 non-null  int64
 1   Date of Purchase  100000 non-null  object
 2   Product Name      100000 non-null  object
 3   Product Weight    100000 non-null  object
 4   Total Price       100000 non-null  object
 5   Retail shop name  100000 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB

In [5]:
# after seeing the dtypes for our dataframe, we need to make some changes
# let us first convert the  Date of Purchase column into datetime

data_frame['Date of Purchase'] = pd.to_datetime(data_frame['Date of Purchase'],
                                                format='%d/%m/%y')
data_frame['Date of Purchase']

0       2020-05-24
1       2020-05-05
2       2020-04-27
3       2020-05-05
4       2020-04-27
           ...
99995   2020-05-24
99996   2020-04-20
99997   2020-01-08
99998   2020-05-05
99999   2020-04-17
Name: Date of Purchase, Length: 100000, dtype: datetime64[ns]

In [6]:
# now we will remove the € symbol using other method, note the data type will continue being object
data_frame['Total Price'] = data_frame['Total Price'].str[1:]
data_frame['Total Price']

0        17
1        19
2        15
3        17
4        13
         ..
99995    25
99996    12
99997    24
99998    22
99999    27
Name: Total Price, Length: 100000, dtype: object

In [7]:
# converting the Total Price into a float 
data_frame['Total Price'] = data_frame['Total Price'].astype('float')
data_frame['Total Price']

0        17.0
1        19.0
2        15.0
3        17.0
4        13.0
         ...
99995    25.0
99996    12.0
99997    24.0
99998    22.0
99999    27.0
Name: Total Price, Length: 100000, dtype: float64

In [8]:
# to remove the "lb" from the product weight column, we will use a similar method to the one used to remove the € from the total price

data_frame['Product Weight'] = data_frame['Product Weight'].str[:-2]
data_frame['Product Weight']

0        4.8
1        3.1
2        1.2
3        3.1
4        4.8
        ...
99995    4.8
99996    3.1
99997    2.7
99998    3.1
99999    4.4
Name: Product Weight, Length: 100000, dtype: object

In [9]:
# now we can convert the column into a float dtype
data_frame['Product Weight'] = data_frame['Product Weight'].astype('float')
data_frame['Product Weight']

0        4.8
1        3.1
2        1.2
3        3.1
4        4.8
        ...
99995    4.8
99996    3.1
99997    2.7
99998    3.1
99999    4.4
Name: Product Weight, Length: 100000, dtype: float64

In [10]:
# use the unique() function to find every unique value from the Product Name column:
data_frame['Product Name'].unique()

array(['Wheat', 'Fruit Juice', 'Vegetables', 'Oil', 'Butter', 'Fruits',
       'Cheese', 'Rice', 'Bread'], dtype=object)

In [12]:
# converting product name into category dtype
data_frame['Product Name'] = data_frame['Product Name'].astype('category')
data_frame['Product Name']

0              Wheat
1        Fruit Juice
2         Vegetables
3                Oil
4              Wheat
            ...
99995            Oil
99996           Rice
99997    Fruit Juice
99998         Butter
99999          Bread
Name: Product Name, Length: 100000, dtype: category
Categories (9, object): ['Bread', 'Butter', 'Cheese', 'Fruit Juice', ..., 'Oil', 'Rice', 'Vegetables', 'Wheat']

In [13]:
data_frame['Retail shop name'].unique()

array(['Fline Store', 'Dello Superstore', 'Javies Retail',
       'Oldi Superstore', 'Kanes Store', 'Kelly Superstore',
       'Visco Retail', 'Rotero Retail'], dtype=object)

In [14]:
data_frame['Retail shop name'] = data_frame['Retail shop name'].astype('category')

data_frame['Retail shop name']

0             Fline Store
1        Dello Superstore
2           Javies Retail
3           Javies Retail
4           Javies Retail
               ...
99995        Visco Retail
99996    Kelly Superstore
99997    Dello Superstore
99998    Dello Superstore
99999        Visco Retail
Name: Retail shop name, Length: 100000, dtype: category
Categories (8, object): ['Dello Superstore', 'Fline Store', 'Javies Retail', 'Kanes Store', 'Kelly Superstore', 'Oldi Superstore', 'Rotero Retail', 'Visco Retail']

In [15]:
# now that we change some of the data types, let us check again with the info() method
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Receipt Id        100000 non-null  int64
 1   Date of Purchase  100000 non-null  datetime64[ns]
 2   Product Name      100000 non-null  category
 3   Product Weight    100000 non-null  float64
 4   Total Price       100000 non-null  float64
 5   Retail shop name  100000 non-null  category
dtypes: category(2), datetime64[ns](1), float64(2), int64(1)
memory usage: 3.2 MB

In [16]:
data_frame = pd.read_csv('files/Chapter04/Data/retail_purchase_missing.csv')
data_frame.head()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
0,10001.0,24/05/20,Wheat,87.0,99.0,NaN
1,NaN,05/05/20,NaN,NaN,25.0,Dello Superstore
2,10003.0,27/04/20,Vegetables,19.0,37.0,Javies Retail
3,10004.0,05/05/20,Oil,99.0,44.0,Javies Retail
4,10005.0,NaN,Wheat,30.0,NaN,Javies Retail

In [18]:
# let us check if there is missing data
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Receipt Id        44 non-null     float64
 1   Date of Purchase  46 non-null     object
 2   Product Name      46 non-null     object
 3   Product Weight    51 non-null     float64
 4   Total Price       51 non-null     float64
 5   Retail shop name  45 non-null     object
dtypes: float64(3), object(3)
memory usage: 2.8+ KB

In [21]:
# to handle missing data, we can use the fillna() method, which replaces every missing calues in a column
# with a chosen value
data_frame.fillna(value = {'Receipt Id': 0, \
                           'Product Weight': 0,\
                           'Total Price': 0},\
                  inplace= True)
data_frame.head()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
0,10001.0,24/05/20,Wheat,87.0,99.0,NaN
1,0.0,05/05/20,NaN,0.0,25.0,Dello Superstore
2,10003.0,27/04/20,Vegetables,19.0,37.0,Javies Retail
3,10004.0,05/05/20,Oil,99.0,44.0,Javies Retail
4,10005.0,NaN,Wheat,30.0,0.0,Javies Retail

In [23]:
# now let us replace the missing values in Date of Purchase column
data_frame['Date of Purchase'].fillna('01/01/99', inplace=True)
data_frame.head()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
0,10001.0,24/05/20,Wheat,87.0,99.0,NaN
1,0.0,05/05/20,NaN,0.0,25.0,Dello Superstore
2,10003.0,27/04/20,Vegetables,19.0,37.0,Javies Retail
3,10004.0,05/05/20,Oil,99.0,44.0,Javies Retail
4,10005.0,01/01/99,Wheat,30.0,0.0,Javies Retail

In [25]:
data_frame.fillna(value = {'Product Name': 'Missing Name',
                           'Retail shop name': 'Missing Name'},
                           inplace = True)
data_frame.head()

,Receipt Id,Date of Purchase,Product Name,Product Weight,Total Price,Retail shop name
0,10001.0,24/05/20,Wheat,87.0,99.0,Missing Name
1,0.0,05/05/20,Missing Name,0.0,25.0,Dello Superstore
2,10003.0,27/04/20,Vegetables,19.0,37.0,Javies Retail
3,10004.0,05/05/20,Oil,99.0,44.0,Javies Retail
4,10005.0,01/01/99,Wheat,30.0,0.0,Javies Retail

In [26]:
# assigning the correct dtypes
data_frame['Date of Purchase'] = \
pd.to_datetime(data_frame['Date of Purchase'], \
                          format='%d/%m/%y')
data_frame['Receipt Id'] = \
data_frame['Receipt Id'].astype('int')
data_frame['Total Price'] = \
data_frame['Total Price'].astype('int')
data_frame['Product Weight'] = \
data_frame['Product Weight'].astype('int')
data_frame['Product Name'] = \
data_frame['Product Name'].astype('category')
data_frame['Retail shop name'] = \
data_frame['Retail shop name'].astype('category')
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Receipt Id        58 non-null     int32
 1   Date of Purchase  58 non-null     datetime64[ns]
 2   Product Name      58 non-null     category
 3   Product Weight    58 non-null     int32
 4   Total Price       58 non-null     int32
 5   Retail shop name  58 non-null     category
dtypes: category(2), datetime64[ns](1), int32(3)
memory usage: 2.1 KB

#### Exercise 4.03 – working with text data using string methods

In [1]:
import pandas as pd

In [4]:
# let us create a series with some text data
s = pd.Series(
    ['          Data Analysis using python with pandas is great',
                'pandas DataFrame and pandas series are useful   ',
                'PYTHON3 PANDAS']
)
s

0              Data Analysis using python with pand...
1     pandas DataFrame and pandas series are useful
2                                       PYTHON3 PANDAS
dtype: object

In [5]:
# using the count() fucntions to count the number of times the word "pandas" appears in the text stored in s, 
# you'll see that pandas is case sensitive
s.str.count('pandas')

0    1
1    2
2    0
dtype: int64

In [6]:
# counting the numbers of characters in each string
s.str.len()

0    57
1    48
2    14
dtype: int64

In [7]:
# in the prevous result we got higher numbers due to leading blank spaces
# let us fix this, and at the same time, we'll get the new lengths
# observe that we need to "invoke" again the "sts" attribute
s.str.strip().str.len()

0    47
1    45
2    14
dtype: int64

In [8]:
# let us check if the the strings start with 'p'
s.str.startswith('p')

0    False
1     True
2    False
dtype: bool

In [9]:
# to make every string to start with "p" we will use a combination of functions and methods
s.str.strip().str.replace('Data', 'pandas').str.lower().str.startswith('p')

0    True
1    True
2    True
dtype: bool

In [10]:
# Use the get_dummies() function to create a DataFrame of dummy variables
# Dummy variables are Booleans that take the True/1 value when the column name is contained in the row.
s.str.get_dummies(' ')

,Analysis,Data,DataFrame,PANDAS,PYTHON3,and,are,great,is,pandas,python,series,useful,using,with
0,1,1,0,0,0,0,0,1,1,1,1,0,0,1,1
1,0,0,1,0,0,1,1,0,0,1,0,1,1,0,0
2,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0

In [11]:
# Use a combination of functions to create a DataFrame of dummy variables that contains only pandas and python:
s = s.str.strip().str.lower()
s.str.get_dummies(' ')[['python', 'pandas']]

   python  pandas
0       1       1
1       0       1
2       0       1